Remove possibly unused maven plugins due to spring deployment error
Trying to fix "Exception in thread "main" java.lang.NoClassDefFoundError: org/springframework/boot/SpringApplication"